import React from 'react';
import { AppProps } from 'next/app';
import 'normalize.css/normalize.css';
import '../styles/index.scss';
import styles from '../styles/app.module.scss';
import Head from 'next/head';
import { gtag } from '../lib/gtag';
import { Router } from 'next/router';

const App = ({ Component, pageProps }: AppProps) => {
  React.useEffect(() => {
    const handleRouteChange = (url: string) => {
      console.log('handleRouteChange', url);
      gtag.pageView(url);
    };
    Router.events.on('routeChangeComplete', handleRouteChange);

    return () => {
      Router.events.off('routeChangeComplete', handleRouteChange);
    };
  }, []);

  return (
    <>
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=M+PLUS+Rounded+1c:wght@300;500;900&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width,initial-scale=1" />

        {/* Generated by https://realfavicongenerator.net/ */}
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#00adb5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <div className={styles.pageWrap}>
        <Component {...pageProps} />
      </div>
    </>
  );
};

export default App;
